### Create Action
POST http://localhost:3000/employees.json 
Content-Type: application/json

{
"first_name": "Dean",
"last_name": "Asshole",
"department_id": "1"
}

### INDEX Action
GET http://localhost:3000/employees.json

### SHOW Action
GET http://localhost:3000/employees/2.json

### DESTROY Action
DELETE http://localhost:3000/employees/2.json