### Create Action Employee
POST http://localhost:3000/employees.json 
Content-Type: application/json

{
"first_name": "Dean",
"last_name": "Asshole",
"department_id": "1"
}

### INDEX Action Employee
GET http://localhost:3000/employees.json

### SHOW Action Employee
GET http://localhost:3000/employees/3.json

### DESTROY Action Employee
DELETE http://localhost:3000/employees/2.json

### UPDATE Action Employee
PATCH http://localhost:3000/employees/3.json 
Content-Type: application/json 

{
  "first_name": "Patrick",
  "last_name": "Pissed now",
  "department_id": "1"
}


### Create Action Department
POST http://localhost:3000/departments.json 
Content-Type: application/json

{
"name": "Sales",
"manager": "Patrick Pissed Now",
"department_code": "c1"
}

### INDEX Action Department
GET http://localhost:3000/departments.json

### SHOW Action Department
GET http://localhost:3000/departments/2.json

### DESTROY Action Department
DELETE http://localhost:3000/departments/1.json

### UPDATE Action Department
PATCH http://localhost:3000/departments/2.json 
Content-Type: application/json 

{
  "name": "Sales",
  "manager": "Kevin",
  "department_code": "c1"
}